language: go

go: 
 - 1.11.x

env:
  - GO111MODULE=on

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
        - sudo add-apt-repository -y ppa:webkit-team/ppa
        - echo 'deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update
        - sudo apt-get install -y libwebkit2gtk-4.0-dev=2.20.1-1 libwebkit2gtk-4.0-37=2.20.1-1 gir1.2-webkit2-4.0=2.20.1-1 libjavascriptcoregtk-4.0-dev=2.20.1-1 gir1.2-javascriptcoregtk-4.0=2.20.1-1 libjavascriptcoregtk-4.0-18=2.20.1-1
    - os: osx
      osx_image: xcode10.2

script:
    #- cd examples/minimal && mkdir -p build && cd build && cmake .. && make && ls -l && cd ../../..
    #- cd examples/timer-cxx && mkdir -p build && cd build && cmake .. && make && ls -l && cd ../../..
  - cd examples/minimal-go && go build && ls -l && cd ../..
  - cd examples/todo-go && go build && ls -l && cd ../..
  - cd examples/page-load-go && go build && ls -l && cd ../..
  - cd examples/window-go && go build && ls -l && cd ../..
