language: go

go: 
 - 1.11.x

matrix:
  include:
    - os: linux
      before_install:
        - sudo add-apt-repository ppa:webkit-team/ppa -y
        - sudo apt-get update
        - sudo apt-get install libwebkit2gtk-4.0-dev -y
    - os: osx
      osx_image: xcode10.2

script:
  - cd examples/minimal && mkdir -p build && cd build && cmake .. && make && ls -l && cd ../../..
  - cd examples/timer-cxx && mkdir -p build && cd build && cmake .. && make && ls -l && cd ../../..
  - cd examples/minimal-go && env GO111MODULE=on go build && ls -l && cd ../..
  - cd examples/todo-go && env GO111MODULE=on go build && ls -l && cd ../..
  - cd examples/page-load-go && env GO111MODULE=on go build && ls -l && cd ../..
  - cd examples/window-go && env GO111MODULE=on go build && ls -l && cd ../..
