version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
      - run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev=2.24.2-1~bpo9+1
      - checkout
      - run: go build
